name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pandas openpyxl pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_welcome_message.py
      id: tests-test-01-welcome-message-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-welcome-message
        setup-command: ''
        command: python -m pytest -v tests/test_01_welcome_message.py
        timeout: 30
        max-score: 5
    - name: tests/test_02_sum_two_numbers.py
      id: tests-test-02-sum-two-numbers-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-sum-two-numbers
        setup-command: ''
        command: python -m pytest -v tests/test_02_sum_two_numbers.py
        timeout: 30
        max-score: 5
    - name: tests/test_03_is_even.py
      id: tests-test-03-is-even-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-is-even
        setup-command: ''
        command: python -m pytest -v tests/test_03_is_even.py
        timeout: 30
        max-score: 5
    - name: tests/test_04_get_number_parity.py
      id: tests-test-04-get-number-parity-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-get-number-parity
        setup-command: ''
        command: python -m pytest -v tests/test_04_get_number_parity.py
        timeout: 30
        max-score: 10
    - name: tests/test_05_fahrenheit_to_celsius.py
      id: tests-test-05-fahrenheit-to-celsius-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-fahrenheit-to-celsius
        setup-command: ''
        command: python -m pytest -v tests/test_05_fahrenheit_to_celsius.py
        timeout: 30
        max-score: 10
    - name: tests/test_06_min_max_mean.py
      id: tests-test-06-min-max-mean-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-min-max-mean
        setup-command: ''
        command: python -m pytest -v tests/test_06_min_max_mean.py
        timeout: 30
        max-score: 10
    - name: tests/test_07_dog_message.py
      id: tests-test-07-dog-message-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-dog-message
        setup-command: ''
        command: python -m pytest -v tests/test_07_dog_message.py
        timeout: 30
        max-score: 10
    - name: tests/test_08_classify_age.py
      id: tests-test-08-classify-age-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-08-classify-age
        setup-command: ''
        command: python -m pytest -v tests/test_08_classify_age.py
        timeout: 30
        max-score: 15
    - name: tests/test_09_calculate_total.py
      id: tests-test-09-calculate-total-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-09-calculate-total
        setup-command: ''
        command: python -m pytest -v tests/test_09_calculate_total.py
        timeout: 30
        max-score: 20
    - name: tests/test_10_input_prompts.py
      id: tests-test-10-input-prompts-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-10-input-prompts
        setup-command: ''
        command: python -m pytest -v tests/test_10_input_prompts.py
        timeout: 30
        max-score: 5
    - name: tests/test_11_printed_messages.py
      id: tests-test-11-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-11-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_11_printed_messages.py
        timeout: 30
        max-score: 4
    - name: tests/test_12_sufficient_comments.py
      id: tests-test-12-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-12-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_12_sufficient_comments.py
        timeout: 30
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-WELCOME-MESSAGE-PY_RESULTS: ${{steps.tests-test-01-welcome-message-py.outputs.result}}
        TESTS-TEST-02-SUM-TWO-NUMBERS-PY_RESULTS: ${{steps.tests-test-02-sum-two-numbers-py.outputs.result}}
        TESTS-TEST-03-IS-EVEN-PY_RESULTS: ${{steps.tests-test-03-is-even-py.outputs.result}}
        TESTS-TEST-04-GET-NUMBER-PARITY-PY_RESULTS: ${{steps.tests-test-04-get-number-parity-py.outputs.result}}
        TESTS-TEST-05-FAHRENHEIT-TO-CELSIUS-PY_RESULTS: ${{steps.tests-test-05-fahrenheit-to-celsius-py.outputs.result}}
        TESTS-TEST-06-MIN-MAX-MEAN-PY_RESULTS: ${{steps.tests-test-06-min-max-mean-py.outputs.result}}
        TESTS-TEST-07-DOG-MESSAGE-PY_RESULTS: ${{steps.tests-test-07-dog-message-py.outputs.result}}
        TESTS-TEST-08-CLASSIFY-AGE-PY_RESULTS: ${{steps.tests-test-08-classify-age-py.outputs.result}}
        TESTS-TEST-09-CALCULATE-TOTAL-PY_RESULTS: ${{steps.tests-test-09-calculate-total-py.outputs.result}}
        TESTS-TEST-10-INPUT-PROMPTS-PY_RESULTS: ${{steps.tests-test-10-input-prompts-py.outputs.result}}
        TESTS-TEST-11-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-11-printed-messages-py.outputs.result}}
        TESTS-TEST-12-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-12-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-welcome-message-py,tests-test-02-sum-two-numbers-py,tests-test-03-is-even-py,tests-test-04-get-number-parity-py,tests-test-05-fahrenheit-to-celsius-py,tests-test-06-min-max-mean-py,tests-test-07-dog-message-py,tests-test-08-classify-age-py,tests-test-09-calculate-total-py,tests-test-10-input-prompts-py,tests-test-11-printed-messages-py,tests-test-12-sufficient-comments-py
